# Testing the game

In [1]:
from wordle_rl import WordleEnv

import gym

from stable_baselines3.her.goal_selection_strategy import GoalSelectionStrategy
from stable_baselines3 import HerReplayBuffer, DQN

In [2]:
import torch

In [3]:
# model = DQN(policy='MultiInputPolicy',     
#     replay_buffer_class=HerReplayBuffer,
#     # Parameters for HER
#     replay_buffer_kwargs=dict(
#         n_sampled_goal=100,
#         goal_selection_strategy='future',
#         online_sampling=True,
#         max_episode_length=6),
#     env=env, 
#     verbose=1)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [11]:
import os
os.getcwd()

'/home/jovyan/wordle-rl/app'

In [14]:
if os.path.exists("./wordle_rl_model_dqn.zip"):
    print("hi")

In [4]:
env = WordleEnv("config.json")

In [5]:
model = DQN.load("./wordle_rl_model_dqn", 
                env, 
                gamma=1,
                replay_buffer_class=HerReplayBuffer,
                # Parameters for HER
                replay_buffer_kwargs=dict(
                    n_sampled_goal=100,
                    goal_selection_strategy='future',
                    online_sampling=True,
                    max_episode_length=6),
                 verbose=1, 
                 device=torch.device(0))

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [4]:
# model = DQN("MlpPolicy",env,verbose=1)

In [20]:
model.learn(total_timesteps=1000)

Correct word: trema
Correct word: whins
Correct word: ripps
Correct word: nippy
Correct word: lutes
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 6        |
|    ep_rew_mean      | 129      |
|    exploration_rate | 0.772    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 1088     |
|    time_elapsed     | 0        |
|    total_timesteps  | 24       |
----------------------------------
Correct word: rubes
Correct word: vibey
Correct word: liven
Correct word: rekes
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 6        |
|    ep_rew_mean      | 192      |
|    exploration_rate | 0.544    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 1132     |
|    time_elapsed     | 0        |
|    total_timesteps  | 48       |
----------------------------------
Correct word: tophi
Correct word: snark
Correct wo

In [21]:
model.save("wordle_rl_model_dqn")

In [9]:
import numpy as np

In [20]:
obs = env.reset()
for i in range(1000):
    action, _state = model.predict(obs, deterministic=False)
    obs, reward, done, info = env.step(action)
    # if i==3:
    #     break;

    env.render()
    if done:
        obs = env.reset()
        break;

Guessed word: cafes
Total reward: 51
Guessed word: smout
Total reward: 54
Guessed word: tills
Total reward: 104
Guessed word: brail
Total reward: 105
Guessed word: brail
Total reward: -4895
Guessed word: brail
Total reward: -9895
{'observation': array([[[ 3.,  1.,  6.,  5., 19.],
        [19., 13., 15., 21., 20.],
        [20.,  9., 12., 12., 19.],
        [ 2., 18.,  1.,  9., 12.],
        [ 2., 18.,  1.,  9., 12.],
        [ 2., 18.,  1.,  9., 12.]],

       [[27., 28., 27., 27., 29.],
        [28., 27., 28., 28., 27.],
        [27., 27., 27., 27., 29.],
        [27., 27., 28., 27., 27.],
        [27., 27., 28., 27., 27.],
        [27., 27., 28., 27., 27.]]]), 'achieved_goal': array([[[ 3.,  1.,  6.,  5., 19.],
        [19., 13., 15., 21., 20.],
        [20.,  9., 12., 12., 19.],
        [ 2., 18.,  1.,  9., 12.],
        [ 2., 18.,  1.,  9., 12.],
        [ 2., 18.,  1.,  9., 12.]],

       [[27., 28., 27., 27., 29.],
        [28., 27., 28., 28., 27.],
        [27., 27., 27., 27., 2

In [14]:
env.obs_state['observation'][0,:2,:]

array([[20., 21., 18.,  4., 19.],
       [12., 25., 19., 15., 12.]])

In [15]:
if any([np.array_equal(env.obs_state['observation'][0,1,:],previous_word) for previous_word in env.obs_state['observation'][0,:2,:]]):
    print(env.penalty)    

-500000000


In [17]:
np.arange(0,1)

array([0])

In [12]:
env.obs_state['observation'][0,:,:]

array([[20., 21., 18.,  4., 19.],
       [12., 25., 19., 15., 12.],
       [12., 25., 19., 15., 12.],
       [ 1., 12.,  5.,  6., 19.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
env.obs_state['observation'][0,2,:]

array([23.,  1., 14.,  7., 19.])

In [23]:
if any([np.array_equal(env.obs_state['observation'][0,2,:],previous_word) for previous_word in env.obs_state['observation'][0,:,:]]):
    print(env.penalty)  

-500000000


In [8]:
test_word = [ord(char) - 96 for char in "dwams"]

In [9]:
test_word

[4, 23, 1, 13, 19]

In [10]:
guess_word = [ord(char) - 96 for char in "kedge"]

In [11]:
guess_word

[11, 5, 4, 7, 5]

In [12]:
for i,num in enumerate(guess_word):
    if guess_word[i] in test_word:
        print(f"Found {guess_word[i]} in test_word")

Found 4 in test_word
