# Testing the game

In [2]:
from wordle_rl import WordleEnv

import gym

from stable_baselines3.her.goal_selection_strategy import GoalSelectionStrategy
from stable_baselines3 import HerReplayBuffer, DQN

In [19]:
env = WordleEnv("config.json")

In [20]:
model = DQN(policy='MultiInputPolicy',     
            replay_buffer_class=HerReplayBuffer,
            # Parameters for HER
            replay_buffer_kwargs=dict(
                n_sampled_goal=100,
                goal_selection_strategy='future',
                online_sampling=True,
                max_episode_length=6),
            env=env, 
            verbose=1)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [ ]:
env.observation_space.spaces

In [4]:
# model = DQN("MlpPolicy",env,verbose=1)

In [21]:
model.learn(total_timesteps=1000000)

Correct word: xysti
Correct word: kauru
Correct word: jupon
Correct word: jougs
Correct word: moved
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 6        |
|    ep_rew_mean      | 104      |
|    exploration_rate | 1        |
| time/               |          |
|    episodes         | 4        |
|    fps              | 939      |
|    time_elapsed     | 0        |
|    total_timesteps  | 24       |
----------------------------------
Correct word: axone
Correct word: maist
Correct word: kaama
Correct word: loden
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 6        |
|    ep_rew_mean      | 123      |
|    exploration_rate | 1        |
| time/               |          |
|    episodes         | 8        |
|    fps              | 1092     |
|    time_elapsed     | 0        |
|    total_timesteps  | 48       |
----------------------------------
Correct word: kinos
Correct word: atlas
Correct wo

AttributeError: 'WordleEnv' object has no attribute 'compute_reward'

In [9]:
import numpy as np

In [42]:
obs = env.reset()
for i in range(1000):
    action, _state = model.predict(obs, deterministic=False)
    obs, reward, done, info = env.step(action)
    # if i==3:
    #     break;

    env.render()
    if done:
        obs = env.reset()
        break;

Correct word: raggs
Guessed word: tokos
Total reward: 50
Guessed word: osmic
Total reward: 51
Guessed word: manos
Total reward: 151
Guessed word: yecch
Total reward: 151
Guessed word: jubas
Total reward: 202
Guessed word: brond
Total reward: 203
{'observation': array([[[20., 15., 11., 15., 19.],
        [15., 19., 13.,  9.,  3.],
        [13.,  1., 14., 15., 19.],
        [25.,  5.,  3.,  3.,  8.],
        [10., 21.,  2.,  1., 19.],
        [ 2., 18., 15., 14.,  4.]],

       [[27., 27., 27., 27., 29.],
        [27., 28., 27., 27., 27.],
        [27., 29., 27., 27., 29.],
        [27., 27., 27., 27., 27.],
        [27., 27., 27., 28., 29.],
        [27., 28., 27., 27., 27.]]]), 'achieved_goal': array([[[20., 15., 11., 15., 19.],
        [15., 19., 13.,  9.,  3.],
        [13.,  1., 14., 15., 19.],
        [25.,  5.,  3.,  3.,  8.],
        [10., 21.,  2.,  1., 19.],
        [ 2., 18., 15., 14.,  4.]],

       [[27., 27., 27., 27., 29.],
        [27., 28., 27., 27., 27.],
        [27., 

In [14]:
env.obs_state['observation'][0,:2,:]

array([[20., 21., 18.,  4., 19.],
       [12., 25., 19., 15., 12.]])

In [15]:
if any([np.array_equal(env.obs_state['observation'][0,1,:],previous_word) for previous_word in env.obs_state['observation'][0,:2,:]]):
    print(env.penalty)    

-500000000


In [17]:
np.arange(0,1)

array([0])

In [12]:
env.obs_state['observation'][0,:,:]

array([[20., 21., 18.,  4., 19.],
       [12., 25., 19., 15., 12.],
       [12., 25., 19., 15., 12.],
       [ 1., 12.,  5.,  6., 19.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
env.obs_state['observation'][0,2,:]

array([23.,  1., 14.,  7., 19.])

In [23]:
if any([np.array_equal(env.obs_state['observation'][0,2,:],previous_word) for previous_word in env.obs_state['observation'][0,:,:]]):
    print(env.penalty)  

-500000000


In [8]:
test_word = [ord(char) - 96 for char in "dwams"]

In [9]:
test_word

[4, 23, 1, 13, 19]

In [10]:
guess_word = [ord(char) - 96 for char in "kedge"]

In [11]:
guess_word

[11, 5, 4, 7, 5]

In [12]:
for i,num in enumerate(guess_word):
    if guess_word[i] in test_word:
        print(f"Found {guess_word[i]} in test_word")

Found 4 in test_word
